### ISSUE TITLE
Duplicated feature labels

### ISSUE THREAD

**Issue by mbacou** [nextgis/QTiles#81] opened 2017-05-23 18:40 UTC
I'm in QGIS 2.18.8, QTiles 1.5.2. Trying to generate tiles from shapefiles with label symbology -- but I end up with duplicated labels. Are there best practices to use labels with tiles?
Thanks!

In QGIS
![image](https://cloud.githubusercontent.com/assets/260325/26370222/2667d25c-3fc5-11e7-8264-1681aef57c37.png)

Rendered tiles in Leaflet
![image](https://cloud.githubusercontent.com/assets/260325/26370316/68ae11ee-3fc5-11e7-9246-4140fda7eee2.png)

**Comment by simgislab** [comment] 2017-05-23 19:00
this is a known problem, meta-tiling (render a set of tiles, not just one) would solve it, pull requests and/or development support are welcome

closing this as duplicate of #1

**Closed by simgislab** 2017-05-23 19:00 UTC

**Comment by mbacou** [comment] 2017-05-23 22:46
Noted thx.
